# 無効にするルール
disabled_rules:
- trailing_whitespace # 余分に改行がある方が視認性が上がる為、無効
- type_name # クラス名は長くして情報を詰めておく必要もある為、無効
- colon
- unused_closure_parameter
- empty_parentheses_with_trailing_closure


# ルール一覧を表示
#- colon
#- control_statement
#- file_length
#- force_cast
#- function_body_length
#- leading_whitespace
#- line_length
#- nesting
#- operator_whitespace
#- return_arrow_whitespace
#- todo
#- trailing_newline
#- variable_name_max_length
#- variable_name_min_length
#- type_body_length
#- variable_name

# 一行の文字列制限を100文字から300文字に変更
line_length: 300

excluded: # Lint対象から外すファイルのあるパスを記述
- Pods

# クラスの行数
type_body_length:
- 200 # warning
- 400 # error

# 関数の長さ
function_body_length:
- 100 # warning
- 200 # error
